### ISSUE TITLE
给转发服务器添加手动延迟和丢包，用以正确认识延迟与丢包对于游戏流畅度的实际影响

### ISSUE THREAD

**Issue by lanyizi** [RA3BattleNet/Relay#1]
目前 `process_control server` 只支持提供转发 IP 以及查询状态这两种功能：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L155
可以新增一种“设置延迟和丢包”的功能，比如说设置一些全局 / class 静态变量，来手动造成延迟和丢包。
（这些变量应该是需要线程安全的）

## 手动造成延迟
在 `do_relay` 里：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L375
可以声明一个 `SteadyTimer` 变量：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L23

之后，在 `do_relay` 函数里面的循环里，收到数据之后：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L378

可以添加类似下面的代码：
```cpp
timer.expires_after(100ms); // 要求等待 100 毫秒
co_await timer.async_wait(); // 开始等待
```
以造成“延迟”的效果。

## 手动造成丢包
`do_relay` 函数，为了完成转发的任务，它在收到数据之后，会把数据发送给另一个玩家：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L394
假如不让它发送，就造成了丢包的效果。可以把发送数据的代码包在一层 `if` 里面，然后使用随机数生成器，按照设置的概率决定是否发送数据。

## 测试
建议既测试 1v1 也测试 3v3，首先需要找到一些认为自己在战网完全不卡、玩起来十分流畅丝滑的人，让他们使用战网的中转服务器联机，然后开始增加转发服务器的延迟和丢包率，同时听取玩家的反馈，来弄清楚什么样的延迟和丢包率能让玩家感觉到卡。

**Comment by richcfno1** [comment]
为什么不试试神奇的弱网工具呢
https://github.com/jagt/clumsy
