### ISSUE TITLE
从转发服务器获取更加具体的状态

### ISSUE THREAD

**Issue by lanyizi** [RA3BattleNet/Relay#2]
可以考虑获取转发服务器对于转发数据的处理时间，以及数据包大小。
## 处理时间
平均处理时间、最大/最小处理时间，大概要比 ping、查询战网的 CPU / 内存 / SWAP 占用率等间接参数，要更加直观一些（
当转发服务器接受到数据之后，开始计时，也就是在下面这个 `co_await` 这行之后：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L378
当转发服务器把数据完全发送出去之后，也就是在下面这个 `co_await` 之后，结束计时：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L394

可以调用 `std::chrono::high_resolution_clock::now()` 来获取“当前时间”，把两个当前时间相减之后，就能得到平均耗时：
```cpp
namespace t = std::chrono;
// chrono 自带的 std::millisecond 是整数，不支持小数，所以精度不够
// std::microsecond 和 nanosecond 可能又太精确了，不一定好用【
// 所以我们自己定义一个使用 double 的毫秒：
using Milliseconds = t::duration<std::milli, double>;
auto begin = t::high_resolution_clock::now();
// ...
auto end = t::high_resolution_clock::now();
double time_elapsed_in_milliseconds = t::duration_cast<Milliseconds>(end - begin).count();
```

显然，这样得到的处理时间，是不包括数据包在网络上的延迟的。不过，网络延迟也许还可以用别的手段（比如说 ping）来得到，而我们这里得到的处理时间，就完全是“数据在服务器上逗留的时间”，我们可以依据这个，来判断“网络卡”究竟是网络环境的锅，还是服务器本身的锅。这个可能要比看 CPU 占用率或者内存占用率要靠谱多了（

可以把每一个连接的处理时间都写到一些全局变量 / class 静态变量里（可能需要注意一下线程安全），从而得到平均处理时间、最小/最大的处理时间，然后在 `get_status` 函数里面返回这些数据：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L180

## 数据包大小
在下面这行可以得到每次转发服务器收到的数据包的大小：
https://github.com/RA3BattleNet/Relay/blob/36e753d1ebcee2d67093147f11dd5238e5fc53be/source/main.cc#L378
这样，我们就能得知游戏平时发送的数据到底有多大。
以后我们测试连接的时候，比如说，让[本地转发“发送数据以测试网络质量”](https://github.com/RA3BattleNet/Client/issues/9)的时候，可以发送一些，大小与游戏数据包相仿的，数据包，从而更加准确的模拟游戏的网络通信，得到更真实的结果

**Comment by richcfno1** [comment]
Done
